--Creamos las credenciales
CREATE LOGIN [IIS APPPOOL\PokeAPI] FROM WINDOWS WITH DEFAULT_DATABASE=[PokeBase], DEFAULT_LANGUAGE=[Español]
GO
CREATE USER PokeUser FOR LOGIN [IIS APPPOOL\PokeAPI];
GO

-- Dar permisos sobre las vistas
GRANT SELECT ON MODULO_COMBATE_RECUPERAR_ULTIMO_COMBATE TO PokeUsuario;
GO
GRANT SELECT ON MODULO_POKEMON_OBTENER_POKEMONES_COMPLETO TO PokeUsuario;
GO

-- Dar permisos sobre los procedimientos
GRANT EXECUTE ON MODULO_COMBATE_INSERTAR_COMBATE TO PokeUsuario;
GO
GRANT EXECUTE ON MODULO_POKEMON_ACTUALIZAR_POKEMON TO PokeUsuario;
GO
GRANT EXECUTE ON MODULO_POKEMON_ELIMINAR_POKEMON TO PokeUsuario;
GO
GRANT EXECUTE ON MODULO_POKEMON_INSERTAR_POKEMON TO PokeUsuario;
GO
GRANT EXECUTE ON MODULO_POKEMON_OBTENER_POKEMON_ID TO PokeUsuario;
GO